### ISSUE TITLE
Performance Expectation

### ISSUE THREAD

**Issue by Keynsie** [nihui/dain-ncnn-vulkan#1]
Very excited to see this project on github, however wondering what kind of performance will be expected after a port to vulkan. Will we see a performance increase over CUDA or significant losses?

**Comment by 0xE1** [comment]
It would be interesting to compare performance on various GPU's from both NVidia and AMD (and maybe other manufacturers as well), and also compare CUDA to Vulkan on same NVidia GPU.

Though for me personally greatest part of this implementation is hardware agnosticism, NVidia have draconian limitations on their consumer GPU's while AMD have the opposite approach (they even provide headless drivers on linux).

**Comment by Keynsie** [comment]
Yeah, I don't really mind the times but was interested as the Vulkan implementation of Waifu2x was actually faster than the CUDA implementation, seems to be the best of both worlds.

**Comment by nihui** [comment]
It runs faster and consumes less VRAM than the original pytorch DAIN.

The main reason is that ncnn is an inference framework, and the architecture design and operator implementation in ncnn are optimized for inference.  The caffe pytorch is mainly used for training.

**Comment by Keynsie** [comment]
Sounds amazing, are you planning on adding a GUI as well? Sounds like the only difficult bit now is waiting :)
