### ISSUE TITLE
how to chose the output file frame rate manually

### ISSUE THREAD

**Issue by BahzBeih** [nihui/dain-ncnn-vulkan#12]
how can I chose the output frame rate manually like to 60fps or 120fps etc instead of the default one >>> 2x frame, I tried -n=4 for example and it didn't work

**Comment by Mar2ck** [comment]
you need to count the input frames. if you have 200 frames at 30 fps then to get 120 fps you need 200*4 aka `-n 800`

**Comment by BahzBeih** [comment]
> you need to count the input frames. if you have 200 frames at 30 fps then to get 120 fps you need 200*4 aka `-n 800`

thanks a lot for your help it worked, I was just hoping there was an easy solution like specify the output directly "frame-rate=60" for example, is there any more detailed reference for using the program?
