### ISSUE TITLE
dain use intel CPU instead of using AMD RX vega 56 GPU problem.

### ISSUE THREAD

**Issue by BahzBeih** [nihui/dain-ncnn-vulkan#15]
peace, i 'am using "dain-ncnn-vulkan-artifact-windows-2019" and use this command :
dain-ncnn-vulkan -g=0 tile-size=128 -i input_frames -o output_frames

[0 Radeon RX Vega]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon RX Vega]  bugsbn1=0  buglbia=0  bugcopc=0  bugihfa=0
[0 Radeon RX Vega]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1

the problem is when I check CPU and GPU usage in task manager it shows dain use about 50-60 % from CPU and 0% from GPU, so is there is something wrong in my code cause this, or this a bug?

my pc specs:
Intel Core i7-4790K @4.5 GHz
ASUS SABERTOOTH Z97 MARK 1
AMD Radeon RX Vega 56
Samsung SSD 860 EVO 500GB
20 Gib ram ddr3
-and the disk where the input and output folder is on Seagate ST1000DM010-2EP102  7200 RPM
-Microsoft Windows 10 Pro Build 18363.959 (1909/November 2019 Update)

**Comment by Mar2ck** [comment]
It shows 0% usage because the program is doing compute work not 3d work. See issue #7 for the solution
