### ISSUE TITLE
Completely dark image

### ISSUE THREAD

**Issue by Rubonnek** [nihui/dain-ncnn-vulkan#16]
**Version**
`master` branch at commit 79257cd14d024f0b9c3e9162244d6a79e9cd3851

**Environment**
Arch Linux running 5.4.68-1-lts kernel
Vulkan 1.2.153

**Issue Description**
I used the following two images:

![death_01](https://user-images.githubusercontent.com/8337880/94994110-9c78dd80-0563-11eb-8b7d-29e5a8beda15.png)
![death_02](https://user-images.githubusercontent.com/8337880/94994111-9c78dd80-0563-11eb-9f2f-f9b588472903.png)

But I got a black image back:

![01](https://user-images.githubusercontent.com/8337880/94994200-33de3080-0564-11eb-8989-5cf7000a3212.png)

**Steps to reproduce:**

After following the build instructions, and inside the `build` folder:
* mkdir input
* Copy the non-black images above as `death_01.png` and `death_02.png` inside the `input` folder.
* Execute:
```
./dain-ncnn-vulkan -0 input/death_01.png -1 input/death_02.png -o input/01.png
```

**Comment by Meister1593** [comment]
I'm trying to run it and it gave me half of black frames (flickering from original to black 50/50), i think it's the same issue
What i noticed, is when i run this app, it gives me lot's and lots of these repeated errors:
```
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
```
Arch, running 5.4 LTS kernel, vulkan-headers + vulkan-icd is presented in system

**Comment by Mar2ck** [comment]
Tried reproducing this on Ubuntu 20.04 using the Github actions build for 79257cd and got this:
![O](https://user-images.githubusercontent.com/6759254/94998998-06b67000-05ae-11eb-84c6-b9a1b6ec4c34.png)

> find_blob_index_by_name failed

This is issue #2, if the program can't find the .bin models at `./` it will just produce black

**Comment by Rubonnek** [comment]
Well, that's right. This is a duplicate of #2. I was able to generate that image after following https://github.com/nihui/dain-ncnn-vulkan/issues/2#issuecomment-696184055.

Thanks for pointing it out!
