### ISSUE TITLE
Image is broken

### ISSUE THREAD

**Issue by Kafu-Ren** [nihui/dain-ncnn-vulkan#18]
![1](https://user-images.githubusercontent.com/70040738/97599292-2c1e8880-1a4b-11eb-800f-7aac532cb544.png)
![2](https://user-images.githubusercontent.com/70040738/97599296-2d4fb580-1a4b-11eb-919e-5e95e082da31.png)
Frame interpolation was performed on the two images with the following command.
The command is as follows:
`dain-ncnn-vulkan -v -0 1.png -1 2.png -o 0.png`

However, all images will produce the following output:
![0](https://user-images.githubusercontent.com/70040738/97599326-350f5a00-1a4b-11eb-8247-4f80c95d7e05.png)
Is it still not working smoothly?

The problem of not finding .bin and .param files was solved by putting dain-ncnn-vulkan.exe file in the directory where .bin and .param are located.

**Comment by Mar2ck** [comment]
These images have an alpha channel (transparency), dain-ncnn/cain-ncnn can only interpolate RGB images not RGBA images. You'll need to remove the alpha channel or if you're using ffmpeg to extract frames use `-pix_fmt rgb24`

**Comment by Kafu-Ren** [comment]
Thank you. It is no longer broken.
