### ISSUE TITLE
output frames failed

### ISSUE THREAD

**Issue by meensukt** [nihui/dain-ncnn-vulkan#27]
I just followed the Tutorial and failed to interpolate frames from this command:

./dain-ncnn-vulkan -i input_frames -o output_frames

The input_frames folder is full of png files named frame_000xx.png 
The output_frames folder is originally empty but after the command, I get the input frames alternating with black images.

The error log in the terminal says:

find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed

**Comment by zocker-160** [comment]
I had the same issue, but I solved it by moving `cain.bin` and `cain.param` out of the `cain` folder and placing them right next to the executable
It should fix the problem.

**Comment by dexeonify** [comment]
> I had the same issue, but I solved it by moving `cain.bin` and `cain.param` out of the `cain` folder and placing them right next to the executable
> This should fix the problem.

This is DAIN, not CAIN, unless I'm missing something here? I tried to grab them from nihui/cain-ncnn-vulkan and neither does that fix the problem. I don't expect it to fix the issue anyways since it's two different repositories.

**Comment by zocker-160** [comment]
@dexeonify OH sorry I confused the two, but the fix still works, since both repos use the same basic code
The executable does **not** look inside the folder for the trained model files

**Comment by dexeonify** [comment]
Isn't that what pull request #20 is supposed to fix? Although it hasn't been merged yet, so this is the workaround for now.

**Comment by zocker-160** [comment]
> Isn't that what pull request #20 is supposed to fix? 

yes exactly

**Comment by nihui** [comment]
fixed in https://github.com/nihui/dain-ncnn-vulkan/commit/f9f849034bf85bb9828bccc68688ca612da8978b

**Comment by QuantumAnomaly** [comment]
I just downloaded the most recent macOS release, but I'm having this problem. Moving the contents of the "best" folder next to the executable did not fix it. If this was patched in 2020, why is the problem still persisting?
