### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by dev-doshi** [nihui/dain-ncnn-vulkan#37]
If I enter this command with the input and output:

`/Users/devdoshi/Documents/dain-ncnn-vulkan-20210210-macos/dain-ncnn-vulkan -i /Users/devdoshi/Documents/input_frames -o /Users/devdoshi/Documents/output_frames`

short: `./dain-ncnn-vulkan -i input_frames/ -o output_frames/`

I get this error:
`zsh: segmentation fault  /Users/devdoshi/Documents/dain-ncnn-vulkan-20210210-macos/dain-ncnn-vulkan -I`

Wikipedia:
> In computing, a segmentation fault (often shortened to segfault) or access violation is a fault, or failure condition, raised by hardware with memory protection, notifying an operating system (OS) the software has attempted to access a restricted area of memory (a memory access violation).

Please fix this bug! 

Thanks 
Dev

**Comment by brenoprata10** [comment]
Same here:
Intel Mac (latest version)

**Comment by dev-doshi** [comment]
> Same here:
> Intel Mac (latest version)

I'am using an M1 Mac (doesn't work), seems like an problem on all (M1 and Intel) macs.

**Comment by dev-doshi** [comment]
@nihui do you even work on this repository anymore (do you even want to update it?)

**Comment by dev-doshi** [comment]
I found the solution:
I tried to create the input and output file in my ./Dowloads folder, but I had to create it in my ./Downloads/waifu2x-ncnn-vulkan and execute every command there.

**Comment by rinogo** [comment]
It worked! Thanks so much for following up and leaving the fix for others.

**Comment by wyick** [comment]
hi there, trying out the method above, and not working on my Intel Mac =( Can anyone help please?

Winsons-MacBook-Pro:dain-ncnn-vulkan-20210210-macos wyick$ ./dain-ncnn-vulkan -i input_frames -o output_frames
[0 Intel(R) Iris(TM) Plus Graphics 655]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) Iris(TM) Plus Graphics 655]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) Iris(TM) Plus Graphics 655]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) Iris(TM) Plus Graphics 655]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
Segmentation fault: 11

**Comment by marxej** [comment]
I'm getting a very similar segfault and have no idea how to move forward! Please advise if you have any tips/ideas 

bash-3.2$ ./cain-ncnn-vulkan -i input_frames -o output_frames
[0 Intel(R) Iris(TM) Graphics 6100]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) Iris(TM) Graphics 6100]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) Iris(TM) Graphics 6100]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) Iris(TM) Graphics 6100]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
Segmentation fault: 11

**Comment by tbhowe** [comment]
I know this is closed, but for anyone interested, the segfault is caused. by `.DS_store' in the input folder. just cd into it and delete and that should solve your issue.
