### ISSUE TITLE
Set output filenames length

### ISSUE THREAD

**Issue by Mar2ck** [nihui/dain-ncnn-vulkan#4]
Right now when using the folder mode the output filenames are always 6 digits long (000001.png). Very long videos are going to exceed 999999.png so please can you add an option to make the filenames longer. For example with a length set to 10 the first image would be 0000000001.png and so on

**Comment by nihui** [comment]
implemented since https://github.com/nihui/dain-ncnn-vulkan/commit/6d508aba8570bfa23cd958e902411103eb81616b

format option now accepts the filename pattern
```
-f %010d.png
```
