### ISSUE TITLE
Looping error (it seems)

### ISSUE THREAD

**Issue by Keynsie** [nihui/dain-ncnn-vulkan#6]
Tried running an interpolation of a 1080p video with the ffmpeg method on the main page and got this running and repeating infinitely.

Looping error of:

find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed

**Comment by Mar2ck** [comment]
Move all the files from best into the same folder as the exec. This is issue #2
