### ISSUE TITLE
GPU usage low?

### ISSUE THREAD

**Issue by Keynsie** [nihui/dain-ncnn-vulkan#7]
managed to get the application to work (thanks mar2ck) however after looking in my task manager, my CPU is at very high usage on all cores and my GPU is at basically 0%. (I'm running a 5700xt and a 3600). The GPU is having it's memory used right now (5.2 out of 8) but everything else is basically idling while CPU is juttering around at about 50% on all cores.

I believe the GPU is right, when I booted it up it said:

[0 AMD Radeon RX 5700 XT]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon RX 5700 XT]  bugsbn1=0  buglbia=0  bugcopc=0  bugihfa=0
[0 AMD Radeon RX 5700 XT]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1

**Comment by Mar2ck** [comment]
Click one of the tabs in task manager (Eg. Copy) and change it to Compute 0. That showed the usage on my friend's PC with radeon

**Comment by Keynsie** [comment]
perfect, glad to see my computer is being used fully. Also found out I can hear my CPU (I think) sucking power through my earphones so I can tell when a frame is going to finish which is quite cool. Thanks :)

**Comment by lextra2** [comment]
alternatively, you can use the sensor read out from hwinfo64
